### ISSUE TITLE
fix(foreman): spawn_worker crashes on missing await for _get_docker_client()

### ISSUE THREAD

**Issue by jmelloy** [jmelloy/pioneer-square#725]
## What's broken

`backend/foreman/tools.py:780` calls the docker client factory without awaiting it:

```python
docker_client = _get_docker_client()
```

`_get_docker_client()` is `async def` (tools.py:106), so this assigns a coroutine
object, not a client. Every subsequent use of `docker_client` (network detection at
line 785, and the actual `docker_client.containers.run(...)` at line 809) raises
`AttributeError: 'coroutine' object has no attribute 'containers'`.

## Evidence (docker logs, this session)

On backend restart, `worker_lifecycle.spawn_replacement_workers()` tried to respawn
124 stale workers from the previous deploy. **All 124 failed** with this exact error:

```
2026-07-04 00:07:48 - foreman.tools - WARNING - Docker network detection failed, starting without explicit network: 'coroutine' object has no attribute 'containers'
/app/backend/worker_lifecycle.py:96: RuntimeWarning: coroutine '_get_docker_client' was never awaited
  result_text, is_error = await _spawn_worker(...)
worker_lifecycle - WARNING - worker_lifecycle: failed to respawn replacement for guild dnsid: Worker pre-registered as w-3f781d but failed to start container: 'coroutine' object has no attribute 'containers'
```

`grep -c "failed to respawn replacement"` on the backend log → **124**. The `workers`
table currently has 124 rows in `spawn_failed` state as a direct result.

## Root cause / history

Introduced in c3020ea (Jun 4, "extract spawn_worker into named function") when the
inline tool-call body was pulled out into the standalone `spawn_worker()` function —
the `await` was dropped in the extraction.

Note: `spawn_worker` was also intentionally excluded from `FOREMAN_TOOLS`
(`backend/foreman_core/tools_schema.py:563`, see #567) pending #551/#564/#566, which
have since merged. That means **the only current caller of `spawn_worker()` is the
stale-worker respawn path** (`worker_lifecycle.spawn_replacement_workers`) — the
foreman AI itself cannot invoke this tool at all right now, so this bug has been
silently killing every automatic worker respawn after a backend restart, with no
other path exercising (or masking) it.

## Fix

Add the missing `await`:

```python
docker_client = await _get_docker_client()
```
